// Typed accessors over public/data/community.json.
//
// The JSON file is generated by the cron and may be absent on first deploys
// (before the user adds any repo via the admin panel). Every accessor here
// treats a missing/invalid file as the empty state and never throws.

import type { CommunityData, CommunityProject } from './community';
import { EMPTY_COMMUNITY_DATA } from './community';

let cachedData: CommunityData | null = null;

/**
 * Fetch community.json from the public URL. Falls back to empty shape on any
 * failure. Caches in-memory for the lifetime of the serverless instance.
 */
async function fetchCommunityJson(): Promise<CommunityData> {
  if (cachedData) return cachedData;
  try {
    const res = await fetch('https://www.alejandro-m-p.com/data/community.json');
    if (!res.ok) return { ...EMPTY_COMMUNITY_DATA };
    const parsed = (await res.json()) as CommunityData;
    if (!parsed || typeof parsed !== 'object' || !Array.isArray(parsed.projects)) {
      return { ...EMPTY_COMMUNITY_DATA };
    }
    cachedData = parsed;
    return cachedData;
  } catch {
    return { ...EMPTY_COMMUNITY_DATA };
  }
}

/**
 * Load community data. Returns the empty shape when `public/data/community.json`
 * is absent, empty, or invalid. Never throws.
 */
export async function loadCommunity(): Promise<CommunityData> {
  return fetchCommunityJson();
}

/**
 * Total merged PR count across all projects. 0 when the file is absent.
 */
export async function getTotalMerged(): Promise<number> {
  const data = await loadCommunity();
  return data.totalMerged ?? data.projects.reduce((sum, p) => sum + p.prs.length, 0);
}

/**
 * Find a single project by its slug (`owner-name`). Undefined when absent.
 */
export async function getProjectBySlug(slug: string): Promise<CommunityProject | undefined> {
  return (await loadCommunity()).projects.find((p) => p.slug === slug);
}